### ISSUE TITLE
Mac OS X

### ISSUE THREAD

**Issue by bjarman** [contentacms/contenta_react_next#3]
I get: 
DONE  Compiled successfully in 19314ms
> Ready on http://app.docker.localhost

but the opening app.docker.localhost in my browser gets nothing.
I have tried adding it to my hosts file but the result is the same.

Is this a OSX issue?

**Comment by spleshka** [comment]
Hi @bjarman, do you use Chrome or Safari? The *.localhost trick is a Chrome's specific thing, otherwise you'd have to add `127.0.0.1 app.docker.localhost` to your `/etc/hosts` files.

**Comment by bjarman** [comment]
I use chrome, not safari.

**Comment by bjarman** [comment]
Attaching to systemseed_node_1

Only output from that command :/

**Comment by bjarman** [comment]
If i tail the log during make up i get: 
systemseed_node_1 exited with code 0
systemseed_traefik_1 exited with code 1

**Comment by spleshka** [comment]
Hi @bjarman, thanks for the info. I was able to reproduce the issue. It looks like the root case of it is outdated traefic image. 

Anyway, I've upgraded the app a little bit. Can you please delete the existing code you have locally, clone the repo again and `make install` and then `make up`? It should make it work as expected. Thanks!

**Comment by bjarman** [comment]
I will try this and post back here with the results. Thanks!

**Comment by bjarman** [comment]
Your fix worked like a charm! Thank you!

**Comment by spleshka** [comment]
@bjarman glad it helped. Pay attention that npm packages haven't been updated for a while, so use them for demo / playground purpose only. If you want to run a real app on this - please upgrade. I've got a plans to bring the packages to the latest version soon though, but just be aware of this.
